"""create notices table

Revision ID: 559c1f4a2aef
Revises: 3eb736056647
Create Date: 2026-07-01 08:08:07.047282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559c1f4a2aef'
down_revision: Union[str, Sequence[str], None] = '40dc3236d46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notices', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.drop_column('notices', 'user_id')
    # ### end Alembic commands ###
